import { createApp } from "vue"
import goodluckUi from "../packages"
import App from "./App.vue"
import router from "./router/index"
import store from "./store"
// import "prismjs/themes/prism-dark.css"
// import "prismjs/themes/prism-coy.css"
// import "prismjs/themes/prism-funky.css"
// import "prismjs/themes/prism-dark.css"
// import "prismjs/themes/prism-solarizedlight.css"
// import "prismjs/themes/prism-tomorrow.css"
// import "prismjs/themes/prism-twilight.css"
// import "prismjs/themes/prism.css"
createApp(App).use(goodluckUi).use(router).use(store).mount("#app")
